version: "2"

services:
  # name of the service, new image will be [oldImageName]_[thisName]... or docker101_node
  node:
    build:
      # context is same as path
      context: .
      dockerfile: Dockerfile
    # this is the outputName of the running container
    container_name: web
    # map ports: [portOutside]:[portInside]
    ports:
      - 5000:3000
